spring:
  application:
    name: NettyServer
  redis:
    database: 0
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
      shutdown-timeout: 1s
  # password: 123456
  # host: 119.45.154.207
  # port: 16379
    host: localhost
    port: 6379
    password: 123456
  #    host: localhost
  #    port: 6379
  #    password:
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/wechat?serverTimezone=GMT
    username: root
    password: q50878215
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 
server:
  port: 8081
#netty 启动端口  
netty:
  port: 9999